version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend_container
    restart: always
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/apartmentsdb
      - NODE_ENV=development
      - PORT=5001
      - JWT_SECRET=fwdhfglwerfhgwklgnwnjilejw7897947839rfnlkfnwlhjr8932743290ujfoijsx!@!#
      - JWT_EXPIRE=12h
      - CLOUDINARY_CLOUD_NAME=dxekwj5zo
      - CLOUDINARY_API_KEY=558422293764766
      - CLOUDINARY_API_SECRET=oRBzjiP8EK8w3zPD9MlABWVZZqM
    depends_on:
      - mongo

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend_container
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5001/api
    depends_on:
      - backend

volumes:
  mongo_data:
